name: update-draft-pr

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: yarn install
        working-directory: actions/update-draft-pr
      - name: Run
        run: yarn start
        working-directory: actions/update-draft-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_EVENT: ${{ toJson(github.event) }}
